import { DashboardStats, ReportFrequency } from "../types";

// The report is generated by a secure server function (/api/generate-report)
// that holds the Gemini key server-side. No AI key is exposed to the browser.
export const generateImpactReport = async (
  data: DashboardStats,
  frequency: ReportFrequency = 'quarterly'
): Promise<string> => {
  const res = await fetch('/api/generate-report', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ data, frequency }),
  });

  const json = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(json.error || 'Failed to generate impact report.');
  }
  return json.report || 'Unable to generate report at this time.';
};
